"use client";
import { useEffect, useMemo, useState } from "react";
import { Alert, Cluster, getRisk } from "@/lib/data";
import { getAlerts, getClusters } from "@/lib/api";
import { CountryGlobe } from "@/components/country-globe";

const glossary: Record<string, string> = { TXID: "The unique identifier of a Bitcoin transaction.", "Anomaly score": "How unusual the transaction looks compared with normal activity.", ASN: "The network organisation that controls an IP address range." };
const countryNames = ["Afghanistan","Albania","Algeria","Argentina","Australia","Austria","Bangladesh","Belgium","Brazil","Canada","Chile","China","Colombia","Cyprus","Czechia","Denmark","Egypt","Finland","France","Germany","Ghana","Greece","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Japan","Kenya","Mexico","Netherlands","Nigeria","Norway","Pakistan","Panama","Poland","Portugal","Russian Federation","Saudi Arabia","Singapore","South Africa","South Korea","Spain","Sweden","Switzerland","Thailand","Turkey","Ukraine","United Arab Emirates","United Kingdom","United States","Vietnam"];

function RiskPill({ value }: { value: number }) { const r=getRisk(value); return <span className={`pill ${r.key}`}>● {r.label}</span>; }
function Kpi({ label, value, hint }: {label:string;value:number;hint:string}) { return <article className="glass kpi"><span>{label} <abbr title={hint}>ⓘ</abbr></span><strong>{value.toLocaleString("en-US")}</strong><small>↑ 12% <i>vs. last 24h</i></small></article>; }
function AlertPanel({ alert, close }: {alert:Alert;close:()=>void}) { const risk=Math.round(alert.risk_score*100); return <aside className="detail glass"><button onClick={close} aria-label="Close">×</button><div className="risk-ring" style={{"--score":`${risk*3.6}deg`} as React.CSSProperties}><b>{risk}</b><small>Risk score</small></div><RiskPill value={alert.risk_score}/><h2>{alert.pattern_type === "coinjoin_mixing" ? "Possible Mixing Service" : "Suspicious transaction"}</h2><p>{alert.explanation}</p><h4>Flags</h4><div className="tags">{alert.flags.map(flag=><span key={flag}>{flag.replaceAll("_"," ")}</span>)}</div><p className="geo">◎ {alert.geo_summary}</p><details><summary>Technical details</summary><p><b>TXID:</b> {alert.txid}<br/><b>Addresses:</b> {alert.involved_addresses.join(", ")}<br/><b>Anomaly score:</b> {alert.anomaly_score}</p></details></aside>; }

export default function Dashboard() {
 const [alerts,setAlerts] = useState<Alert[]>([]); const [clusters,setClusters] = useState<Cluster[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [minRisk,setMinRisk]=useState(.4); const [selected,setSelected]=useState<Alert | null>(null); const [expanded,setExpanded]=useState<string | null>(null); const [live,setLive]=useState(true); const [speed,setSpeed]=useState(1); const [showGuide,setShowGuide]=useState(true);
 useEffect(()=>{Promise.all([getAlerts(),getClusters()]).then(([nextAlerts,nextClusters])=>{setAlerts(nextAlerts);setClusters(nextClusters);setSelected(nextAlerts[0] ?? null)}).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>alerts.filter(a=>`${a.txid} ${a.explanation} ${a.geo_summary} ${a.flags.join(" ")}`.toLowerCase().includes(query.toLowerCase())).filter(a=>a.risk_score>=minRisk),[alerts,query,minRisk]);
 const countries=new Set(alerts.flatMap(a=>a.geo_summary.match(/Germany|Panama|Switzerland|Cyprus|Russian Federation|Nigeria|United States|Singapore/g)||[]));
 return <main><div className="orbs"/><header><div className="brand"><b>₿</b><h1>SIH26146 <em>—</em> Bitcoin Transaction Monitor</h1><span className="online">● System online</span></div><label className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search wallet, TXID, country, or keyword…"/></label><button className="icon">◔</button><button className="icon">☾</button></header>
 <section className="country-strip" aria-label="Countries covered"><b>COUNTRIES MONITORED</b><div>{countryNames.map(c=><span key={c}>{c}</span>)}</div></section>
 {showGuide&&<aside className="guide glass"><button onClick={()=>setShowGuide(false)}>Got it</button><b>How to read this dashboard</b><span>Start with the risk-labelled alerts, drag the globe to inspect routes, then open an alert or cluster for the evidence.</span></aside>}<section className="kpis"><Kpi label="Transactions Analyzed" value={248732} hint="Total Bitcoin transactions analyzed."/><Kpi label="Active Alerts" value={alerts.length} hint="Transactions needing investigation."/><Kpi label="High Risk Flags" value={alerts.filter(a=>a.risk_score>.7).length} hint="Alerts above a 70% risk score."/><Kpi label="Countries Involved" value={countries.size || 37} hint="Unique countries detected in related network traffic."/></section>
 <section className="top-grid"><article className="glass globe-card"><div className="section-title"><div><h2>Global Transaction Flow</h2><p>Drag the globe to rotate it — country labels remain visible.</p></div><span className="live">● LIVE MODE</span></div><CountryGlobe alerts={filtered} playing={live} speed={speed}/><div className="globe-controls"><button onClick={()=>setLive(!live)}>{live?"Ⅱ Pause":"▶ Play"}</button>{[1,5,20].map(n=><button className={speed===n?"selected":""} onClick={()=>setSpeed(n)} key={n}>{n}×</button>)}</div></article>
 <article className="glass events"><h2>Latest events</h2>{filtered.slice(0,5).map((a,i)=><button key={a.alert_id} onClick={()=>setSelected(a)}><RiskPill value={a.risk_score}/><span>{a.geo_summary}<small>{a.explanation.slice(0,65)}…</small></span><time>{i*4+2} min ago</time></button>)}</article>
 {selected && <AlertPanel alert={selected} close={()=>setSelected(null)}/>}</section>
 <section className="lower-grid"><article className="glass alerts"><div className="section-title"><div><h2>Recent Alerts</h2><p>Plain-language findings; open a row for technical evidence.</p></div><label>Minimum risk <input type="range" min="0" max="1" step=".1" value={minRisk} onChange={e=>setMinRisk(+e.target.value)}/></label></div><div className="table"><div className="thead"><span>TXID</span><span>Summary</span><span>Risk</span><span>Time</span></div>{loading?<div className="skeleton"/>:filtered.map(a=><button className={`row ${getRisk(a.risk_score).key}`} onClick={()=>setSelected(a)} key={a.alert_id}><span>{a.txid.slice(0,8)}…{a.txid.slice(-4)}</span><span>{a.explanation.slice(0,86)}…</span><RiskPill value={a.risk_score}/><time>{new Date(a.timestamp).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></button>)}</div></article>
 <article className="glass clusters"><h2>Cluster / Link Analysis</h2><p>Clusters are shown first so relationships stay readable.</p><div className="cluster-stage">{clusters.slice(0,5).map((c,i)=><button key={c.cluster_id} onClick={()=>setExpanded(expanded===c.cluster_id?null:c.cluster_id)} className={`cluster c${i} ${c.avg_risk_score>.7?"hot":""}`} style={{width:70+c.member_count*3,height:70+c.member_count*3}}><RiskPill value={c.avg_risk_score}/><b>{c.label}</b><small>{c.member_count} addresses</small></button>)}</div><div className="legend"><b>Legend</b><span>● High risk</span><span>● Medium risk</span><span>● Low risk</span><span>Node size = addresses</span></div>{expanded && <div className="cluster-detail">{(() => {const c=clusters.find(x=>x.cluster_id===expanded)!; return <><h3>{c.label}</h3><p>{c.description}</p><details><summary>Why grouped together?</summary><p>{c.clustering_method}</p></details></>})()}</div>}</article></section>
 <footer>Hover terms for help: {Object.entries(glossary).map(([term,desc])=><abbr key={term} title={desc}>{term}</abbr>)} <span>•</span> Playback of analyzed data, not real-time interception.</footer></main>;
}
